name: Bugtracker
description: ...

labels: ["bug", "help wanted"]
assignees: ["whynotix"]

body:
  - type: checkboxes
    attributes:
      label: Checklist
      options:
        - label: I think this a module bug
          required: true
        - label: I dont found any issues like my problem
          required: true
        - label: I install latest module version
          required: true

  - type: textarea
    attributes:
      label: explain, describe bug and actions to get this bug
      description: explain, describe bug and actions to get this bug
      placeholder: |
        When i [...], module return [...]
    validations:
      required: true

  - type: textarea
    attributes:
      label: Code example
      description: Code example
      placeholder: |
        ...
      render: python3

  - type: textarea
    attributes:
      label: Logs
      description: Console logs (if you have it)
      placeholder: |
        ...
